version: '3.8'
services:
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql